// Code generated by cmd/lexgen for "json"; DO NOT EDIT.

package gotreesitter

import "unicode/utf8"

func scanJsonGen(l *Lexer, startState uint32, startPos int, startRow, startCol uint32) (Token, bool) {
	src := l.source
	state := int(startState)
	scanPos := startPos
	scanRow := startRow
	scanCol := startCol
	tokenStartPos := startPos
	tokenStartRow := startRow
	tokenStartCol := startCol
	acceptPos := -1
	var acceptRow, acceptCol uint32
	acceptStartPos := startPos
	acceptStartRow := startRow
	acceptStartCol := startCol
	var acceptSymbol Symbol
	acceptSkip := false
	acceptPriorityBest := int16(32767)
	eofHops := 0
	for {
		if state < 0 || state >= 44 {
			break
		}
		switch state {
		case 22:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 1
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 23:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 2
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 24:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 3
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 25:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 4
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 26:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 5
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 27:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 6
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 28:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 7
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 29:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 8
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 30:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 8
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 31:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 8
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 32:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 8
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 33:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 8
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 34:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 9
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 35:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 10
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 36:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 10
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 37:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 10
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 38:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 10
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 39:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 11
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 40:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 12
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 41:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 13
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 42:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 14
				acceptSkip = false
				acceptPriorityBest = 0
			}
		case 43:
			if acceptPos < 0 || 0 < acceptPriorityBest || (0 == acceptPriorityBest && scanPos > acceptPos) {
				acceptPos = scanPos
				acceptRow = scanRow
				acceptCol = scanCol
				acceptStartPos = tokenStartPos
				acceptStartRow = tokenStartRow
				acceptStartCol = tokenStartCol
				acceptSymbol = 14
				acceptSkip = false
				acceptPriorityBest = 0
			}
		}
		if scanPos >= len(src) {
			switch state {
			case 0:
				if eofHops <= 44 {
					state = 21
					eofHops++
					continue
				}
			case 20:
				if eofHops <= 44 {
					state = 21
					eofHops++
					continue
				}
			}
			break
		}
		eofHops = 0
		bb := src[scanPos]
		var r rune
		var size int
		if bb < 0x80 {
			r = rune(bb)
			size = 1
		} else {
			r, size = utf8.DecodeRune(src[scanPos:])
		}
		next := -1
		skipTransition := false
		switch state {
		case 0:
			switch {
			case r == 34:
				next = 28
			case r == 44:
				next = 23
			case r == 45:
				next = 7
			case r == 47:
				next = 3
			case r == 48:
				next = 35
			case r == 58:
				next = 25
			case r == 91:
				next = 26
			case r == 92:
				next = 18
			case r == 93:
				next = 27
			case r == 102:
				next = 8
			case r == 110:
				next = 17
			case r == 116:
				next = 14
			case r == 123:
				next = 22
			case r == 125:
				next = 24
			case r >= 9 && r <= 13:
				next = 20
				skipTransition = true
			case r == 32:
				next = 20
				skipTransition = true
			case r >= 49 && r <= 57:
				next = 36
			}
		case 1:
			switch {
			case r == 10:
				next = 2
				skipTransition = true
			case r == 34:
				next = 28
			case r == 47:
				next = 29
			case r == 92:
				next = 18
			case r >= 9 && r <= 13:
				next = 32
			case r == 32:
				next = 32
			case r >= 1 && r <= 1114111:
				next = 33
			}
		case 2:
			switch {
			case r == 34:
				next = 28
			case r == 47:
				next = 3
			case r >= 9 && r <= 13:
				next = 2
				skipTransition = true
			case r == 32:
				next = 2
				skipTransition = true
			}
		case 3:
			switch {
			case r == 42:
				next = 5
			case r == 47:
				next = 43
			}
		case 4:
			switch {
			case r == 42:
				next = 4
			case r == 47:
				next = 42
			case r >= 1 && r <= 1114111:
				next = 5
			}
		case 5:
			switch {
			case r == 42:
				next = 4
			case r >= 1 && r <= 1114111:
				next = 5
			}
		case 6:
			switch {
			case r == 45:
				next = 19
			case r >= 48 && r <= 57:
				next = 38
			}
		case 7:
			switch {
			case r == 48:
				next = 35
			case r >= 49 && r <= 57:
				next = 36
			}
		case 8:
			switch {
			case r == 97:
				next = 11
			}
		case 9:
			switch {
			case r == 101:
				next = 39
			}
		case 10:
			switch {
			case r == 101:
				next = 40
			}
		case 11:
			switch {
			case r == 108:
				next = 15
			}
		case 12:
			switch {
			case r == 108:
				next = 41
			}
		case 13:
			switch {
			case r == 108:
				next = 12
			}
		case 14:
			switch {
			case r == 114:
				next = 16
			}
		case 15:
			switch {
			case r == 115:
				next = 10
			}
		case 16:
			switch {
			case r == 117:
				next = 9
			}
		case 17:
			switch {
			case r == 117:
				next = 13
			}
		case 18:
			switch {
			case r == 34:
				next = 34
			case r == 47:
				next = 34
			case r == 92:
				next = 34
			case r == 98:
				next = 34
			case r == 102:
				next = 34
			case r == 110:
				next = 34
			case r == 114:
				next = 34
			case r >= 116 && r <= 117:
				next = 34
			}
		case 19:
			switch {
			case r >= 48 && r <= 57:
				next = 38
			}
		case 20:
			switch {
			case r == 34:
				next = 28
			case r == 44:
				next = 23
			case r == 45:
				next = 7
			case r == 47:
				next = 3
			case r == 48:
				next = 35
			case r == 58:
				next = 25
			case r == 91:
				next = 26
			case r == 93:
				next = 27
			case r == 102:
				next = 8
			case r == 110:
				next = 17
			case r == 116:
				next = 14
			case r == 123:
				next = 22
			case r == 125:
				next = 24
			case r >= 9 && r <= 13:
				next = 20
				skipTransition = true
			case r == 32:
				next = 20
				skipTransition = true
			case r >= 49 && r <= 57:
				next = 36
			}
		case 29:
			switch {
			case r == 42:
				next = 31
			case r == 47:
				next = 33
			case r >= 1 && r <= 9:
				next = 33
			case r >= 11 && r <= 33:
				next = 33
			case r >= 35 && r <= 91:
				next = 33
			case r >= 93 && r <= 1114111:
				next = 33
			}
		case 30:
			switch {
			case r == 42:
				next = 30
			case r == 47:
				next = 33
			case r >= 1 && r <= 9:
				next = 31
			case r >= 11 && r <= 33:
				next = 31
			case r >= 35 && r <= 91:
				next = 31
			case r >= 93 && r <= 1114111:
				next = 31
			}
		case 31:
			switch {
			case r == 42:
				next = 30
			case r >= 1 && r <= 9:
				next = 31
			case r >= 11 && r <= 33:
				next = 31
			case r >= 35 && r <= 91:
				next = 31
			case r >= 93 && r <= 1114111:
				next = 31
			}
		case 32:
			switch {
			case r == 47:
				next = 29
			case r == 9:
				next = 32
			case r >= 11 && r <= 13:
				next = 32
			case r == 32:
				next = 32
			case r >= 1 && r <= 8:
				next = 33
			case r >= 14 && r <= 33:
				next = 33
			case r >= 35 && r <= 91:
				next = 33
			case r >= 93 && r <= 1114111:
				next = 33
			}
		case 33:
			switch {
			case r >= 1 && r <= 9:
				next = 33
			case r >= 11 && r <= 33:
				next = 33
			case r >= 35 && r <= 91:
				next = 33
			case r >= 93 && r <= 1114111:
				next = 33
			}
		case 35:
			switch {
			case r == 46:
				next = 37
			case r == 69:
				next = 6
			case r == 101:
				next = 6
			}
		case 36:
			switch {
			case r == 46:
				next = 37
			case r == 69:
				next = 6
			case r == 101:
				next = 6
			case r >= 48 && r <= 57:
				next = 36
			}
		case 37:
			switch {
			case r == 69:
				next = 6
			case r == 101:
				next = 6
			case r >= 48 && r <= 57:
				next = 37
			}
		case 38:
			switch {
			case r >= 48 && r <= 57:
				next = 38
			}
		case 43:
			switch {
			case r >= 1 && r <= 9:
				next = 43
			case r >= 11 && r <= 1114111:
				next = 43
			}
		}
		if next < 0 {
			break
		}
		scanPos += size
		if r == '\n' {
			scanRow++
			scanCol = 0
		} else {
			scanCol += uint32(size)
		}
		if skipTransition {
			tokenStartPos = scanPos
			tokenStartRow = scanRow
			tokenStartCol = scanCol
			acceptPos = -1
			acceptSymbol = 0
			acceptSkip = false
		}
		state = next
	}
	if acceptPos < 0 {
		return Token{}, false
	}
	l.pos = acceptPos
	l.row = acceptRow
	l.col = acceptCol
	if acceptSkip {
		return Token{
			StartByte:  uint32(acceptStartPos),
			EndByte:    uint32(acceptPos),
			StartPoint: Point{Row: acceptStartRow, Column: acceptStartCol},
			EndPoint:   Point{Row: acceptRow, Column: acceptCol},
		}, true
	}
	return Token{
		Symbol:     acceptSymbol,
		Text:       bytesToStringNoCopy(src[acceptStartPos:acceptPos]),
		StartByte:  uint32(acceptStartPos),
		EndByte:    uint32(acceptPos),
		StartPoint: Point{Row: acceptStartRow, Column: acceptStartCol},
		EndPoint:   Point{Row: acceptRow, Column: acceptCol},
	}, true
}
