// Command lexgen generates a switch-DFA lexer for a language, replacing the
// runtime table-DFA interpreter (Lexer.scan) with a self-contained nested-switch
// state machine — the same shape tree-sitter C emits as ts_lex. The generated
// function is verified bit-for-bit against the table scan() by the differential
// test (lexer_codegen_<lang>_test.go), so a codegen bug is caught before the
// generated lexer is ever trusted.
//
// M1 (spike) scope: languages whose lexer DFA uses only the core features —
// transitions (incl. skip), longest-match accept (all AcceptPriority == 0), and
// EOF chains. It REFUSES languages using immediate tokens, zero-width tokens,
// non-zero accept priorities, or default transitions (those are M2). json fits.
//
// Usage: go run ./cmd/lexgen <lang>   (writes <lang>_lexer_gen.go + _gen_data_test.go)
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"

	gts "github.com/odvcencio/gotreesitter"
	"github.com/odvcencio/gotreesitter/grammars"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: lexgen <lang>")
		os.Exit(2)
	}
	name := os.Args[1]
	entry := grammars.DetectLanguageByName(name)
	if entry == nil || entry.Language == nil {
		fmt.Fprintf(os.Stderr, "unknown language: %s\n", name)
		os.Exit(1)
	}
	lang := entry.Language()
	states := lang.LexStates

	// M1 guard: refuse features the spike generator doesn't emit yet.
	for i, b := range lang.ImmediateTokens {
		if b {
			fmt.Fprintf(os.Stderr, "unsupported (M2): %s has immediate token %d\n", name, i)
			os.Exit(1)
		}
	}
	for i, b := range lang.ZeroWidthTokens {
		if b {
			fmt.Fprintf(os.Stderr, "unsupported (M2): %s has zero-width token %d\n", name, i)
			os.Exit(1)
		}
	}
	for i, s := range states {
		if s.AcceptPriority != 0 {
			fmt.Fprintf(os.Stderr, "unsupported (M2): %s state %d has AcceptPriority %d\n", name, i, s.AcceptPriority)
			os.Exit(1)
		}
		if s.Default >= 0 {
			fmt.Fprintf(os.Stderr, "unsupported (M2): %s state %d has Default transition\n", name, i)
			os.Exit(1)
		}
		if s.Skip {
			fmt.Fprintf(os.Stderr, "unsupported (M2): %s state %d has Skip-accept\n", name, i)
			os.Exit(1)
		}
	}

	Title := strings.Title(name)
	gen := emitScan(name, Title, states)
	writeGofmt(name+"_lexer_gen.go", gen)

	data := emitData(name, states)
	writeGofmt(name+"_lexer_gen_data_test.go", data)

	fmt.Printf("generated %s_lexer_gen.go (+_data_test.go) for %d states\n", name, len(states))
}

// emitScan writes scan<Title>Gen: a self-contained nested-switch translation of
// Lexer.scan for a core-feature DFA. Longest-match (priority 0): a later/longer
// accept always wins, so the accept test is simply scanPos > acceptPos.
func emitScan(name, Title string, states []gts.LexState) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by cmd/lexgen for %q; DO NOT EDIT.\n\n", name)
	fmt.Fprintf(&b, "package gotreesitter\n\nimport \"unicode/utf8\"\n\n")
	fmt.Fprintf(&b, "func scan%sGen(l *Lexer, startState uint32, startPos int, startRow, startCol uint32) (Token, bool) {\n", Title)
	b.WriteString(`	src := l.source
	state := int(startState)
	scanPos := startPos
	scanRow := startRow
	scanCol := startCol
	tokenStartPos := startPos
	tokenStartRow := startRow
	tokenStartCol := startCol
	acceptPos := -1
	var acceptRow, acceptCol uint32
	acceptStartPos := startPos
	acceptStartRow := startRow
	acceptStartCol := startCol
	var acceptSymbol Symbol
	eofHops := 0
	for {
		if state < 0 || state >= numStates {
			break
		}
`)
	// Accept block: for accepting states, longest-match record.
	b.WriteString("\t\tswitch state {\n")
	for i, s := range states {
		if s.AcceptToken == 0 {
			continue
		}
		fmt.Fprintf(&b, "\t\tcase %d:\n", i)
		b.WriteString("\t\t\tif acceptPos < 0 || scanPos > acceptPos {\n")
		fmt.Fprintf(&b, "\t\t\t\tacceptPos = scanPos; acceptRow = scanRow; acceptCol = scanCol\n")
		fmt.Fprintf(&b, "\t\t\t\tacceptStartPos = tokenStartPos; acceptStartRow = tokenStartRow; acceptStartCol = tokenStartCol\n")
		fmt.Fprintf(&b, "\t\t\t\tacceptSymbol = %d\n", s.AcceptToken)
		b.WriteString("\t\t\t}\n")
	}
	b.WriteString("\t\t}\n")
	// EOF handling: chain via st.EOF, capped at numStates.
	b.WriteString(`		if scanPos >= len(src) {
			switch state {
`)
	for i, s := range states {
		if s.EOF >= 0 {
			fmt.Fprintf(&b, "\t\t\tcase %d:\n\t\t\t\tif eofHops <= numStates {\n\t\t\t\t\tstate = %d; eofHops++; continue\n\t\t\t\t}\n", i, s.EOF)
		}
	}
	b.WriteString(`			}
			break
		}
		eofHops = 0
		bb := src[scanPos]
		var r rune
		var size int
		if bb < 0x80 {
			r = rune(bb)
			size = 1
		} else {
			r, size = utf8.DecodeRune(src[scanPos:])
		}
		next := -1
		skipTransition := false
		switch state {
`)
	// Transition block: per-state rune-range switch.
	for i, s := range states {
		if len(s.Transitions) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\t\tcase %d:\n\t\t\tswitch {\n", i)
		for _, tr := range s.Transitions {
			cond := rangeCond(tr.Lo, tr.Hi)
			if tr.Skip {
				fmt.Fprintf(&b, "\t\t\tcase %s:\n\t\t\t\tnext = %d; skipTransition = true\n", cond, tr.NextState)
			} else {
				fmt.Fprintf(&b, "\t\t\tcase %s:\n\t\t\t\tnext = %d\n", cond, tr.NextState)
			}
		}
		b.WriteString("\t\t\t}\n")
	}
	b.WriteString(`		}
		if next < 0 {
			break
		}
		scanPos += size
		if r == '\n' {
			scanRow++
			scanCol = 0
		} else {
			scanCol += uint32(size)
		}
		if skipTransition {
			tokenStartPos = scanPos
			tokenStartRow = scanRow
			tokenStartCol = scanCol
			acceptPos = -1
			acceptSymbol = 0
		}
		state = next
	}
	if acceptPos < 0 {
		return Token{}, false
	}
	l.pos = acceptPos
	l.row = acceptRow
	l.col = acceptCol
	return Token{
		Symbol:     acceptSymbol,
		Text:       bytesToStringNoCopy(src[acceptStartPos:acceptPos]),
		StartByte:  uint32(acceptStartPos),
		EndByte:    uint32(acceptPos),
		StartPoint: Point{Row: acceptStartRow, Column: acceptStartCol},
		EndPoint:   Point{Row: acceptRow, Column: acceptCol},
	}, true
}
`)
	out := b.String()
	// Inline the state count as a literal (the body template uses numStates).
	out = strings.ReplaceAll(out, "numStates", fmt.Sprint(len(states)))
	return out
}

func rangeCond(lo, hi rune) string {
	if lo == hi {
		return fmt.Sprintf("r == %d", lo)
	}
	return fmt.Sprintf("r >= %d && r <= %d", lo, hi)
}

// emitData writes the lang's LexStates as a test-only var so the internal
// differential test can build a table Lexer without importing grammars.
func emitData(name string, states []gts.LexState) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by cmd/lexgen for %q; DO NOT EDIT.\n\n", name)
	b.WriteString("package gotreesitter\n\n")
	fmt.Fprintf(&b, "var %sLexStatesForDiff = []LexState{\n", name)
	for _, s := range states {
		fmt.Fprintf(&b, "\t{AcceptToken: %d, AcceptPriority: %d, Skip: %v, Default: %d, EOF: %d, Transitions: []LexTransition{",
			s.AcceptToken, s.AcceptPriority, s.Skip, s.Default, s.EOF)
		for _, tr := range s.Transitions {
			fmt.Fprintf(&b, "{Lo: %d, Hi: %d, NextState: %d, Skip: %v}, ", tr.Lo, tr.Hi, tr.NextState, tr.Skip)
		}
		b.WriteString("}},\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func writeGofmt(path, src string) {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		// Write unformatted for debugging, then fail.
		os.WriteFile(path+".raw", []byte(src), 0o644)
		fmt.Fprintf(os.Stderr, "gofmt %s: %v (wrote %s.raw)\n", path, err, path)
		os.Exit(1)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
		os.Exit(1)
	}
}
