// Command lexgen generates a switch-DFA lexer for a language, replacing the
// runtime table-DFA interpreter (Lexer.scan) with a self-contained nested-switch
// state machine — the same shape tree-sitter C emits as ts_lex. The generated
// function is verified bit-for-bit against the table scan() by the differential
// test (lexer_codegen_<lang>_test.go), so a codegen bug is caught before the
// generated lexer is ever trusted.
//
// It replicates the full scan() semantics: longest-match with AcceptPriority
// tiebreak, immediate-token rejection after whitespace, zero-width visibility,
// skip-accept (whitespace) states, EOF chains, default transitions, and UTF-8.
// The per-state feature flags are inlined as constants so the Go compiler folds
// the dead branches for languages that don't use a given feature.
//
// Usage: go run ./cmd/lexgen <lang>   (writes <lang>_lexer_gen.go + _gen_data_test.go)
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"

	gts "github.com/odvcencio/gotreesitter"
	"github.com/odvcencio/gotreesitter/grammars"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: lexgen <lang>")
		os.Exit(2)
	}
	name := os.Args[1]
	entry := grammars.DetectLanguageByName(name)
	if entry == nil || entry.Language == nil {
		fmt.Fprintf(os.Stderr, "unknown language: %s\n", name)
		os.Exit(1)
	}
	lang := entry.Language()

	Title := strings.Title(name)
	writeGofmt(name+"_lexer_gen.go", emitScan(name, Title, lang))
	writeGofmt(name+"_lexer_gen_data_test.go", emitData(name, lang))
	fmt.Printf("generated %s_lexer_gen.go (+_data_test.go) for %d states\n", name, len(lang.LexStates))
}

func immediate(lang *gts.Language, t gts.Symbol) bool {
	return t > 0 && int(t) < len(lang.ImmediateTokens) && lang.ImmediateTokens[t]
}

func zeroWidthAllowed(lang *gts.Language, t gts.Symbol) bool {
	// Mirror Lexer.allowsZeroWidthToken: a nil/empty table allows ALL tokens
	// to match zero-width (so no zeroWidthVisible rejection is emitted).
	if len(lang.ZeroWidthTokens) == 0 {
		return true
	}
	return int(t) < len(lang.ZeroWidthTokens) && lang.ZeroWidthTokens[t]
}

// acceptGuard returns the &&-joined guard that must hold for state s to record
// an accept, mirroring scan()'s `!(isImmediate && skippedWhitespace) &&
// !zeroWidthVisible`, with the per-state feature flags resolved to constants
// (an always-true clause is omitted).
func acceptGuard(lang *gts.Language, s gts.LexState) string {
	var parts []string
	if immediate(lang, s.AcceptToken) {
		// !(immediate && skippedWhitespace) == !skippedWhitespace == tokenStartPos == startPos
		parts = append(parts, "tokenStartPos == startPos")
	}
	if s.AcceptToken > 0 && !zeroWidthAllowed(lang, s.AcceptToken) {
		// !zeroWidthVisible == !(scanPos == tokenStartPos)
		parts = append(parts, "scanPos != tokenStartPos")
	}
	return strings.Join(parts, " && ")
}

func emitScan(name, Title string, lang *gts.Language) string {
	states := lang.LexStates
	var b bytes.Buffer
	fmt.Fprintf(&b, "//go:build lexgen\n\n// Code generated by cmd/lexgen for %q; DO NOT EDIT.\n\n", name)
	b.WriteString("package gotreesitter\n\nimport \"unicode/utf8\"\n\n")
	fmt.Fprintf(&b, "func scan%sGen(l *Lexer, startState uint32, startPos int, startRow, startCol uint32) (Token, bool) {\n", Title)
	b.WriteString(`	src := l.source
	state := int(startState)
	scanPos := startPos
	scanRow := startRow
	scanCol := startCol
	tokenStartPos := startPos
	tokenStartRow := startRow
	tokenStartCol := startCol
	acceptPos := -1
	var acceptRow, acceptCol uint32
	acceptStartPos := startPos
	acceptStartRow := startRow
	acceptStartCol := startCol
	var acceptSymbol Symbol
	acceptSkip := false
	acceptPriorityBest := int16(32767)
	eofHops := 0
	for {
		if state < 0 || state >= NUMSTATES {
			break
		}
`)
	// Accept block: states that accept a token OR are skip (whitespace) states.
	b.WriteString("\t\tswitch state {\n")
	for i, s := range states {
		if s.AcceptToken == 0 && !s.Skip {
			continue
		}
		fmt.Fprintf(&b, "\t\tcase %d:\n", i)
		indent := "\t\t\t"
		if g := acceptGuard(lang, s); g != "" {
			fmt.Fprintf(&b, "\t\t\tif %s {\n", g)
			indent = "\t\t\t\t"
		}
		fmt.Fprintf(&b, "%sif acceptPos < 0 || %d < acceptPriorityBest || (%d == acceptPriorityBest && scanPos > acceptPos) {\n", indent, s.AcceptPriority, s.AcceptPriority)
		fmt.Fprintf(&b, "%s\tacceptPos = scanPos; acceptRow = scanRow; acceptCol = scanCol\n", indent)
		fmt.Fprintf(&b, "%s\tacceptStartPos = tokenStartPos; acceptStartRow = tokenStartRow; acceptStartCol = tokenStartCol\n", indent)
		fmt.Fprintf(&b, "%s\tacceptSymbol = %d\n", indent, s.AcceptToken)
		fmt.Fprintf(&b, "%s\tacceptSkip = %v\n", indent, s.Skip)
		fmt.Fprintf(&b, "%s\tacceptPriorityBest = %d\n", indent, s.AcceptPriority)
		fmt.Fprintf(&b, "%s}\n", indent)
		if acceptGuard(lang, s) != "" {
			b.WriteString("\t\t\t}\n")
		}
	}
	b.WriteString("\t\t}\n")
	// EOF handling: chain via st.EOF, capped at NUMSTATES.
	b.WriteString("\t\tif scanPos >= len(src) {\n\t\t\tswitch state {\n")
	for i, s := range states {
		if s.EOF >= 0 {
			fmt.Fprintf(&b, "\t\t\tcase %d:\n\t\t\t\tif eofHops <= NUMSTATES {\n\t\t\t\t\tstate = %d; eofHops++; continue\n\t\t\t\t}\n", i, s.EOF)
		}
	}
	b.WriteString(`			}
			break
		}
		eofHops = 0
		bb := src[scanPos]
		var r rune
		var size int
		if bb < 0x80 {
			r = rune(bb)
			size = 1
		} else {
			r, size = utf8.DecodeRune(src[scanPos:])
		}
		next := -1
		skipTransition := false
		switch state {
`)
	// Transition block: per-state rune-range switch + optional default.
	for i, s := range states {
		if len(s.Transitions) == 0 && s.Default < 0 {
			continue
		}
		fmt.Fprintf(&b, "\t\tcase %d:\n\t\t\tswitch {\n", i)
		for _, tr := range s.Transitions {
			if tr.Skip {
				fmt.Fprintf(&b, "\t\t\tcase %s:\n\t\t\t\tnext = %d; skipTransition = true\n", rangeCond(tr.Lo, tr.Hi), tr.NextState)
			} else {
				fmt.Fprintf(&b, "\t\t\tcase %s:\n\t\t\t\tnext = %d\n", rangeCond(tr.Lo, tr.Hi), tr.NextState)
			}
		}
		if s.Default >= 0 {
			// scan() applies Default only when no range matched; skipTransition
			// stays false for a default transition.
			fmt.Fprintf(&b, "\t\t\tdefault:\n\t\t\t\tnext = %d\n", s.Default)
		}
		b.WriteString("\t\t\t}\n")
	}
	b.WriteString(`		}
		if next < 0 {
			break
		}
		scanPos += size
		if r == '\n' {
			scanRow++
			scanCol = 0
		} else {
			scanCol += uint32(size)
		}
		if skipTransition {
			tokenStartPos = scanPos
			tokenStartRow = scanRow
			tokenStartCol = scanCol
			acceptPos = -1
			acceptSymbol = 0
			acceptSkip = false
		}
		state = next
	}
	if acceptPos < 0 {
		return Token{}, false
	}
	l.pos = acceptPos
	l.row = acceptRow
	l.col = acceptCol
	if acceptSkip {
		return Token{
			StartByte:  uint32(acceptStartPos),
			EndByte:    uint32(acceptPos),
			StartPoint: Point{Row: acceptStartRow, Column: acceptStartCol},
			EndPoint:   Point{Row: acceptRow, Column: acceptCol},
		}, true
	}
	return Token{
		Symbol:     acceptSymbol,
		Text:       bytesToStringNoCopy(src[acceptStartPos:acceptPos]),
		StartByte:  uint32(acceptStartPos),
		EndByte:    uint32(acceptPos),
		StartPoint: Point{Row: acceptStartRow, Column: acceptStartCol},
		EndPoint:   Point{Row: acceptRow, Column: acceptCol},
	}, true
}
`)
	return strings.ReplaceAll(b.String(), "NUMSTATES", fmt.Sprint(len(states)))
}

func rangeCond(lo, hi rune) string {
	if lo == hi {
		return fmt.Sprintf("r == %d", lo)
	}
	return fmt.Sprintf("r >= %d && r <= %d", lo, hi)
}

// emitData writes the lang's LexStates + immediate/zero-width token tables as
// test-only vars so the internal differential test can build a table Lexer that
// matches the runtime exactly, without importing grammars.
func emitData(name string, lang *gts.Language) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "//go:build lexgen\n\n// Code generated by cmd/lexgen for %q; DO NOT EDIT.\n\n", name)
	b.WriteString("package gotreesitter\n\n")
	fmt.Fprintf(&b, "var %sLexStatesForDiff = []LexState{\n", name)
	for _, s := range lang.LexStates {
		fmt.Fprintf(&b, "\t{AcceptToken: %d, AcceptPriority: %d, Skip: %v, Default: %d, EOF: %d, Transitions: []LexTransition{",
			s.AcceptToken, s.AcceptPriority, s.Skip, s.Default, s.EOF)
		for _, tr := range s.Transitions {
			fmt.Fprintf(&b, "{Lo: %d, Hi: %d, NextState: %d, Skip: %v}, ", tr.Lo, tr.Hi, tr.NextState, tr.Skip)
		}
		b.WriteString("}},\n")
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "var %sImmediateForDiff = %s\n\n", name, boolSlice(lang.ImmediateTokens))
	fmt.Fprintf(&b, "var %sZeroWidthForDiff = %s\n", name, boolSlice(lang.ZeroWidthTokens))
	return b.String()
}

func boolSlice(s []bool) string {
	if len(s) == 0 {
		return "[]bool(nil)"
	}
	var b strings.Builder
	b.WriteString("[]bool{")
	for i, v := range s {
		if i > 0 {
			b.WriteByte(',')
		}
		if v {
			b.WriteString("true")
		} else {
			b.WriteString("false")
		}
	}
	b.WriteString("}")
	return b.String()
}

func writeGofmt(path, src string) {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		os.WriteFile(path+".raw", []byte(src), 0o644)
		fmt.Fprintf(os.Stderr, "gofmt %s: %v (wrote %s.raw)\n", path, err, path)
		os.Exit(1)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
		os.Exit(1)
	}
}
